# Generated by Django 3.0.3 on 2020-03-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200307_2249'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='data_created',
            new_name='date_created',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
